[package]
name = "optijpeg"
version = "0.2.0"
edition = "2024"
description = "A cross-platform, lossless JPEG optimizer that strips metadata"
license = "MIT"
publish = false

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
libc = "0.2"
lexical-sort = "0.3.1"
mozjpeg-sys = { version = "2.2.3", default-features = false, features = ["unwinding"] }
rayon = "1.12.0"
tempfile = "3.20"
walkdir = "2.5"

[dev-dependencies]
assert_cmd = "2.0"
jpeg-decoder = "0.3"
predicates = "3.1"

[profile.release]
codegen-units = 1
lto = true
opt-level = 2
strip = "symbols"
